services:

  pg:
    image: postgres
    env_file:
      - ./.env
      - ./.env.template
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./.env
      - ./.env.template
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"

  django:
    build: .
    command: sh -c "cd esn &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - pg
