# Generated by Django 5.2.6 on 2025-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="contact",
        ),
        migrations.AddField(
            model_name="networknode",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="networknode",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="networknode",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="networknode",
            name="house_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="networknode",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
